// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAy0RoLo9VsntTqzdpEt4gnsYLbXECMJs',
    appId: '1:890277765700:web:79cf2f6000da3ffd0ed211',
    messagingSenderId: '890277765700',
    projectId: 'my-job-portal-07110',
    authDomain: 'my-job-portal-07110.firebaseapp.com',
    storageBucket: 'my-job-portal-07110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdGgkfvczX29_wVt4_aLLxo7H9xzD5CM',
    appId: '1:890277765700:android:c1b9d594b7c28b700ed211',
    messagingSenderId: '890277765700',
    projectId: 'my-job-portal-07110',
    storageBucket: 'my-job-portal-07110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGS4X2QxCr6NN9b9HI-oFlyytclQXuzg',
    appId: '1:890277765700:ios:3a204079fae015550ed211',
    messagingSenderId: '890277765700',
    projectId: 'my-job-portal-07110',
    storageBucket: 'my-job-portal-07110.firebasestorage.app',
    iosBundleId: 'com.example.agJobportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGS4X2QxCr6NN9b9HI-oFlyytclQXuzg',
    appId: '1:890277765700:ios:3a204079fae015550ed211',
    messagingSenderId: '890277765700',
    projectId: 'my-job-portal-07110',
    storageBucket: 'my-job-portal-07110.firebasestorage.app',
    iosBundleId: 'com.example.agJobportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAy0RoLo9VsntTqzdpEt4gnsYLbXECMJs',
    appId: '1:890277765700:web:440ed3564bb151d90ed211',
    messagingSenderId: '890277765700',
    projectId: 'my-job-portal-07110',
    authDomain: 'my-job-portal-07110.firebaseapp.com',
    storageBucket: 'my-job-portal-07110.firebasestorage.app',
  );
}
